// <auto-generated />
using System;
using CleanArchitecture.Identity.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Identity.Migrations
{
    [DbContext(typeof(ApplicationIdentityDbContext))]
    partial class ApplicationIdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppPermission<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", "Identity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Can Insert Data",
                            Name = "CanInsert"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Can Update Data",
                            Name = "CanUpdate"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Can Delete Data",
                            Name = "CanDelete"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Can Print Data",
                            Name = "CanPrint"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Can Import Data",
                            Name = "CanImport"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Can Export Data",
                            Name = "CanExport"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Can View Data",
                            Name = "CanView"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("557d96c5-6ab6-40b9-b2a3-47166e861366"),
                            Name = "Administrators",
                            NormalizedName = "ADMINISTRATORS"
                        },
                        new
                        {
                            Id = new Guid("447d96c5-6ab6-40b9-b2a3-47166e861366"),
                            Name = "Supervisors",
                            NormalizedName = "SUPERVISORS"
                        },
                        new
                        {
                            Id = new Guid("337d96c5-6ab6-40b9-b2a3-47166e861366"),
                            Name = "Users",
                            NormalizedName = "USERS"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolesClaims", "Identity");
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b345d5d-4714-401f-b124-32836d210679"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cbe6bc7f-41f9-49d9-8243-0b6c2a6bed39",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEH+Zk/4d8MIuhovPyzP01aq0pGpI5yH/6NA9a6ayXu2NN/pqB4IsZQiBWe7aIN1BaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "123",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("2b345d5d-4714-401f-b124-32836d210679"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e72d63d6-6d43-48f0-af20-4017c9c25f34",
                            Email = "supervisor@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERVISOR@GMAIL.COM",
                            NormalizedUserName = "SUPERVISOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEPSb5HjgXBGffK3NTVGylwISbrpuY4aVkR4Uz2X1pkltfR5K/AFzpxZL5lG7HI9zrA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "123",
                            TwoFactorEnabled = false,
                            UserName = "supervisor"
                        },
                        new
                        {
                            Id = new Guid("3b345d5d-4714-401f-b124-32836d210679"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "12c0dd97-1f76-4e70-bb4f-3285a1dde7d1",
                            Email = "user@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEA9m3NCDCLubvVOs94+H0iUDN7Mw76QSHXYS9MX+SU/+6zyDBsgV0Jipx6hwiwPpNg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "123",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersClaims", "Identity");
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UsersLogins", "Identity");
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedOn");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UsersPermissions", "Identity", t =>
                        {
                            t.Property("UpdatedOn")
                                .HasColumnName("UpdatedOn1");
                        });

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1b345d5d-4714-401f-b124-32836d210679"),
                            PermissionId = 1,
                            CreatedOn = new DateTime(2024, 4, 26, 7, 21, 7, 432, DateTimeKind.Local).AddTicks(9785),
                            UpdatedOn = new DateTime(2024, 4, 26, 7, 21, 7, 433, DateTimeKind.Local).AddTicks(11)
                        },
                        new
                        {
                            UserId = new Guid("1b345d5d-4714-401f-b124-32836d210679"),
                            PermissionId = 2,
                            CreatedOn = new DateTime(2024, 4, 26, 7, 21, 7, 433, DateTimeKind.Local).AddTicks(38),
                            UpdatedOn = new DateTime(2024, 4, 26, 7, 21, 7, 433, DateTimeKind.Local).AddTicks(42)
                        },
                        new
                        {
                            UserId = new Guid("1b345d5d-4714-401f-b124-32836d210679"),
                            PermissionId = 3,
                            CreatedOn = new DateTime(2024, 4, 26, 7, 21, 7, 433, DateTimeKind.Local).AddTicks(48),
                            UpdatedOn = new DateTime(2024, 4, 26, 7, 21, 7, 433, DateTimeKind.Local).AddTicks(58)
                        },
                        new
                        {
                            UserId = new Guid("1b345d5d-4714-401f-b124-32836d210679"),
                            PermissionId = 7,
                            CreatedOn = new DateTime(2024, 4, 26, 7, 21, 7, 433, DateTimeKind.Local).AddTicks(73),
                            UpdatedOn = new DateTime(2024, 4, 26, 7, 21, 7, 433, DateTimeKind.Local).AddTicks(76)
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersRoles", "Identity");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1b345d5d-4714-401f-b124-32836d210679"),
                            RoleId = new Guid("557d96c5-6ab6-40b9-b2a3-47166e861366")
                        },
                        new
                        {
                            UserId = new Guid("1b345d5d-4714-401f-b124-32836d210679"),
                            RoleId = new Guid("447d96c5-6ab6-40b9-b2a3-47166e861366")
                        },
                        new
                        {
                            UserId = new Guid("1b345d5d-4714-401f-b124-32836d210679"),
                            RoleId = new Guid("337d96c5-6ab6-40b9-b2a3-47166e861366")
                        },
                        new
                        {
                            UserId = new Guid("2b345d5d-4714-401f-b124-32836d210679"),
                            RoleId = new Guid("447d96c5-6ab6-40b9-b2a3-47166e861366")
                        },
                        new
                        {
                            UserId = new Guid("2b345d5d-4714-401f-b124-32836d210679"),
                            RoleId = new Guid("337d96c5-6ab6-40b9-b2a3-47166e861366")
                        },
                        new
                        {
                            UserId = new Guid("3b345d5d-4714-401f-b124-32836d210679"),
                            RoleId = new Guid("337d96c5-6ab6-40b9-b2a3-47166e861366")
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsersTokens", "Identity");
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitecture.Identity.Entities.AppRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitecture.Identity.Entities.AppUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitecture.Identity.Entities.AppUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserPermission", b =>
                {
                    b.HasOne("CleanArchitecture.Identity.Entities.AppPermission<int>", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Identity.Entities.AppUser<System.Guid>", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserRole<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitecture.Identity.Entities.AppRole<System.Guid>", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Identity.Entities.AppUser<System.Guid>", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUserToken<System.Guid>", b =>
                {
                    b.HasOne("CleanArchitecture.Identity.Entities.AppUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppPermission<int>", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppRole<System.Guid>", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CleanArchitecture.Identity.Entities.AppUser<System.Guid>", b =>
                {
                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
