// <auto-generated />
using System;
using CleanArchitecture.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230920072919_SeedingUsersData")]
    partial class SeedingUsersData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Membership.Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 9, 20, 10, 29, 19, 401, DateTimeKind.Local).AddTicks(346),
                            Email = "admin1@gmail.com",
                            Name = "admin1",
                            Password = "123",
                            Role = "admins",
                            UpdatedBy = 0,
                            UpdatedDate = new DateTime(2023, 9, 20, 10, 29, 19, 401, DateTimeKind.Local).AddTicks(400)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 9, 20, 10, 29, 19, 401, DateTimeKind.Local).AddTicks(408),
                            Email = "admin2@gmail.com",
                            Name = "admin2",
                            Password = "123",
                            Role = "admins",
                            UpdatedBy = 0,
                            UpdatedDate = new DateTime(2023, 9, 20, 10, 29, 19, 401, DateTimeKind.Local).AddTicks(411)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 9, 20, 10, 29, 19, 401, DateTimeKind.Local).AddTicks(430),
                            Email = "user1@gmail.com",
                            Name = "user1",
                            Password = "456",
                            Role = "users",
                            UpdatedBy = 0,
                            UpdatedDate = new DateTime(2023, 9, 20, 10, 29, 19, 401, DateTimeKind.Local).AddTicks(433)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2023, 9, 20, 10, 29, 19, 401, DateTimeKind.Local).AddTicks(437),
                            Email = "user2@gmail.com",
                            Name = "user2",
                            Password = "456",
                            Role = "users",
                            UpdatedBy = 0,
                            UpdatedDate = new DateTime(2023, 9, 20, 10, 29, 19, 401, DateTimeKind.Local).AddTicks(440)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
